name: image_painter_rotate
description: A flutter package for drawing over images. Supports rotating, color,
  strokeWidth, different paintModes and exporting image.
version: 1.0.2
homepage: https://github.com/satoyan/yellowQ-Flutter-Image-Painter

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0 # Or the latest version
  build_runner: ^2.0.0 # Use the latest version
  build_test: ^2.0.0 # Use the latest version
